/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { BTCb } from "./BTCb";
export type { Endpoint } from "./Endpoint";
export type { STGtoken } from "./STGtoken";
