/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { Endpoint__factory } from "./Endpoint__factory";
export { STGtoken__factory } from "./STGtoken__factory";
